# Numpy

In [2]:
import numpy as np

## Numpy Arrays(ndarray)

In [4]:
np.array([1, 2, 3])

array([1, 2, 3])

In [13]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=complex)

In [10]:
type(matrix[0][0])

numpy.int64

In [14]:
matrix

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j],
       [7.+0.j, 8.+0.j, 9.+0.j]])

In [15]:
ndarray = np.array([1, 2, 3], dtype=np.uint8) # unsigned + - integer 8bit

In [17]:
ndarray

array([1, 2, 3], dtype=uint8)

In [18]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [19]:
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
array1 + array2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

## Shape

In [23]:
ndarray = np.array([[1, 2], [3, 4], [5, 6]])
ndarray

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
ndarray.shape

(3, 2)

In [34]:
ndarray.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
ndarray1 = np.array([1, 2, 3])
ndarray2 = np.array([[1, 2, 3]])

In [27]:
ndarray1

array([1, 2, 3])

In [28]:
print(ndarray1.shape)

(3,)


In [30]:
ndarray2

array([1, 2, 3])

In [33]:
print(ndarray2.shape)

(1, 3)


In [37]:
expand_ndarray = np.expand_dims(ndarray1, axis=1)

In [38]:
expand_ndarray.shape

(3, 1)

In [39]:
np.squeeze(expand_ndarray)

array([1, 2, 3])

In [40]:
expand_ndarray

array([[1],
       [2],
       [3]])

In [45]:
ndarray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
ndarray.shape

(3, 3)

In [46]:
ndarray.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## IndexingとSlicing

In [3]:
ndarray = np.array([1, 2, 3, 4])

In [4]:
ndarray

array([1, 2, 3, 4])

In [5]:
ndarray[-1]

4

In [6]:
ndarray = np.array([[1, 2], [3, 4], [5, 6]])
ndarray

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
ndarray[0, 0]

1

In [11]:
ndarray = np.array([1, 2, 3, 4])
ndarray

array([1, 2, 3, 4])

In [12]:
ndarray[1:3]

array([2, 3])

In [14]:
ndarray[:-2]

array([1, 2])

In [15]:
ndarray[:]

array([1, 2, 3, 4])

In [16]:
ndarray = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

In [17]:
ndarray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [18]:
ndarray[:3]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
ndarray[0:2, 0:3]

array([[1, 2, 3],
       [5, 6, 7]])

## np.arrange(), np.linspace(), np.logspace()

In [24]:
np.arange(10, 1, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [23]:
list(range(2, 15, 4))

[2, 6, 10, 14]

In [26]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [27]:
np.logspace(0, 3, 10)

array([   1.        ,    2.15443469,    4.64158883,   10.        ,
         21.5443469 ,   46.41588834,  100.        ,  215.443469  ,
        464.15888336, 1000.        ])

In [28]:
np.linspace(0, 3, 10)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [29]:
10 ** 0.3333

2.1542693374042363

In [30]:
shape = (3, 4)
np.zeros(shape)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
shape = (5, 4)
np.ones(shape)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [35]:
np.eye(4, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

## np.randomを使って乱数生成

### np.random.rand()

In [37]:
## 擬似乱数　psuedo random
np.random.rand(3, 4)

array([[0.95564184, 0.21264545, 0.32786523, 0.2020688 ],
       [0.64113281, 0.111155  , 0.06119846, 0.90116625],
       [0.72413266, 0.41679347, 0.10084936, 0.22781643]])

### np.radom.seed

In [39]:
np.random.seed(1)
np.random.rand()

0.417022004702574

In [42]:
np.random.rand()

0.00011437481734488664

### np.random.randn()

In [47]:
np.random.randn(10, 10)

array([[ 1.77260763, -1.11036305,  0.18121427,  0.56434487, -0.56651023,
         0.7299756 ,  0.37299379,  0.53381091, -0.0919733 ,  1.91382039],
       [ 0.33079713,  1.14194252, -1.12959516, -0.85005238,  0.96082   ,
        -0.21741818,  0.15851488,  0.87341823, -0.11138337, -1.03803876],
       [-1.00947983, -1.05825656,  0.65628408, -0.06249159, -1.73865429,
         0.103163  , -0.62166685,  0.27571804, -1.09067489, -0.60998525],
       [ 0.30641238,  1.69182613, -0.74795374, -0.58079722, -0.11075397,
         2.04202875,  0.44752069,  0.68338423,  0.02288597,  0.85723427],
       [ 0.18393058, -0.41611158,  1.25005005,  1.24829979, -0.75767414,
         0.58829416,  0.34685933,  1.3670327 ,  0.67371607, -1.2915627 ],
       [-0.84824392, -0.16659957,  0.91719602,  0.08025059,  0.22823877,
        -0.8804768 ,  0.27812885, -0.07015677,  0.62958793, -1.81342356],
       [ 1.54744858,  0.32505743, -0.21191292, -1.54672407,  1.04520063,
         1.01037548,  0.07083664,  0.71758983

In [48]:
np.random.normal(10, 1)

9.22089304496586

### np.random.randint

In [50]:
np.random.randint(10, 100, (2, 3))

array([[29, 36, 96],
       [17, 63, 57]])

### np.random.choice()

In [53]:
a = [1, 2, 3]
np.random.choice(a)

3

In [54]:
index_pool = np.arange(0, 10, 2)
index_pool

array([0, 2, 4, 6, 8])

## 統計量を求める

In [66]:
std_norm = np.random.randn(5, 5)
std_norm

array([[ 0.75041164,  0.52946532,  0.13770121,  0.07782113,  0.61838026],
       [ 0.23249456,  0.68255141, -0.31011677, -2.43483776,  1.0388246 ],
       [ 2.18697965,  0.44136444, -0.10015523, -0.13644474, -0.11905419],
       [ 0.01740941, -1.12201873, -0.51709446, -0.99702683,  0.24879916],
       [-0.29664115,  0.49521132, -0.17470316,  0.98633519,  0.2135339 ]])

In [67]:
#最大値
std_norm.max()

2.1869796469742577

In [68]:
#最小値
std_norm.min()

-2.434837764107139

In [69]:
#最大値のindexを取得
std_norm.argmax()

10

In [71]:
std_norm.flatten()[10]

2.1869796469742577

In [72]:
#平均を取得
std_norm.mean()

0.09796760705535781

In [73]:
#中央値を取得
np.median(std_norm)

0.13770120999738608

In [78]:
#中央値 vs 平均値
import time
a = np.random.randn(1000, 1000)
before = time.time()
np.median(a)
after_median = time.time()
np.mean(a)
after_mean = time.time()
print('median took {} sec'.format(after_median - before))
print('mean took {} sec'.format(after_mean - after_median))

median took 0.04061603546142578 sec
mean took 0.002196788787841797 sec


In [79]:
#標準偏差を取得
np.std(std_norm)

0.8395214126060696

## 数学で使う便利関数

In [80]:
# 平方根 square root
np.sqrt([1, 2, 3, 4])

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [81]:
# log (logarithm)
x = np.linspace(1, 10, 10)
np.log(x)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [82]:
x

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [84]:
# 指数関数 Exponential function
np.exp(2)

7.38905609893065

In [86]:
# 合計 (summation)
array = np.arange(1, 11)
np.sum(array)

55

In [87]:
ndarray = array.reshape(2, 5)
ndarray

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [89]:
np.sum(ndarray, axis=0)

array([ 7,  9, 11, 13, 15])

In [91]:
# 絶対値 absolute value
array = np.arange(-10, 0)

In [92]:
np.abs(array)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

## np.nanとnp.isnan()

In [93]:
# NaN : Not a Number

In [94]:
np.log(-100)

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


nan

In [95]:
type(np.nan)

float

In [96]:
a = None
a is None

True

In [98]:
np.isnan(np.log(-100))

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


True

## その他便利関数

### np.clip

In [100]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
np.clip(array, 3, 7)

array([3, 3, 3, 3, 4, 5, 6, 7, 7, 7])

In [102]:
1e-4

0.0001

## numpy array のコンディション

In [103]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### np.where

In [105]:
np.where(array > 3, 1, 0)

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [106]:
np.where(array > 3)

(array([4, 5, 6, 7, 8, 9]),)

In [109]:
# filter
array > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [108]:
array + 3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [110]:
ndarray = array.reshape(2, 5)
ndarray[ndarray>3]

array([4, 5, 6, 7, 8, 9])

In [111]:
(ndarray > 3).all()

False

In [112]:
(ndarray > 3).any()

True

In [114]:
(ndarray > 3).all(axis=0)

array([False, False, False, False,  True])

In [115]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
ndarray

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [117]:
array = np.array([1, 1, 2, 3, 4, 2, 3, 4, 5])
array

array([1, 1, 2, 3, 4, 2, 3, 4, 5])

In [118]:
np.unique(array)

array([1, 2, 3, 4, 5])

In [120]:
np.unique(array, return_counts=True)

(array([1, 2, 3, 4, 5]), array([2, 2, 2, 2, 1]))

### np.bincount()

In [121]:
np.bincount(array)

array([0, 2, 2, 2, 2, 1])

### np.concatenate()とnp.stack()

In [125]:
ndarray_even = np.arange(0, 18, 2).reshape(3, 3)
ndarray_even

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [129]:
ndarray_odd = np.arange(1, 19, 2).reshape(3, 3)
ndarray_odd

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [131]:
np.concatenate([ndarray_even, ndarray_odd])

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [138]:
np.stack([ndarray_even, ndarray_odd], axis=-1)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

In [139]:
_

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

In [140]:
stacked_array = _

In [141]:
stacked_array.shape

(3, 3, 2)

In [142]:
stacked_array

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

### np.transpose.T

In [144]:
ndarray = np.random.randn(3, 4)
ndarray

array([[ 0.03747826,  0.0665842 ,  0.01464636, -0.34728375],
       [-0.95771789, -1.88508128, -0.31399211,  0.84988276],
       [-0.38997855,  1.13908551, -0.60175086, -0.11793318]])

In [145]:
ndarray.shape

(3, 4)

In [146]:
np.transpose(ndarray)

array([[ 0.03747826, -0.95771789, -0.38997855],
       [ 0.0665842 , -1.88508128,  1.13908551],
       [ 0.01464636, -0.31399211, -0.60175086],
       [-0.34728375,  0.84988276, -0.11793318]])

In [147]:
transpose_ndarray = _

In [148]:
transpose_ndarray.shape

(4, 3)

In [149]:
ndarray.T

array([[ 0.03747826, -0.95771789, -0.38997855],
       [ 0.0665842 , -1.88508128,  1.13908551],
       [ 0.01464636, -0.31399211, -0.60175086],
       [-0.34728375,  0.84988276, -0.11793318]])

In [152]:
ndarray = np.random.randn(3, 4, 5)

In [153]:
ndarray.T

array([[[ 0.30151287,  0.09124433,  1.00297554],
        [-0.37603302,  1.37523323,  1.63914394],
        [ 0.42484403, -0.1438355 ,  0.80390793],
        [-0.97843066,  1.80074855,  1.17254232]],

       [[ 0.37217085,  0.29322409,  0.30631624],
        [ 1.45850967,  2.68396465, -1.67463226],
        [-1.71942804, -0.06882065,  1.18591072],
        [ 0.74135179, -1.08901229,  1.99842926]],

       [[-2.10572101,  0.53519911,  0.42869907],
        [ 0.75783182, -0.75520203,  1.17718837],
        [ 0.97652113, -0.49928009,  0.32199584],
        [-0.04399561, -1.23582281, -1.26996018]],

       [[-0.89990131,  1.00997382,  1.97868335],
        [ 0.73381127,  0.70141567,  0.31112613],
        [-0.54260306, -0.66920766, -1.30108795],
        [-0.70465384,  1.66758504,  2.06173294]],

       [[-0.40734368, -1.05569967,  0.69192854],
        [-1.67192917,  1.91142061, -0.27363147],
        [-1.31010735, -0.54022649,  1.03982799],
        [-0.20208207,  0.55487304,  0.37793722]]])

In [154]:
ndarray

array([[[ 0.30151287,  0.37217085, -2.10572101, -0.89990131,
         -0.40734368],
        [-0.37603302,  1.45850967,  0.75783182,  0.73381127,
         -1.67192917],
        [ 0.42484403, -1.71942804,  0.97652113, -0.54260306,
         -1.31010735],
        [-0.97843066,  0.74135179, -0.04399561, -0.70465384,
         -0.20208207]],

       [[ 0.09124433,  0.29322409,  0.53519911,  1.00997382,
         -1.05569967],
        [ 1.37523323,  2.68396465, -0.75520203,  0.70141567,
          1.91142061],
        [-0.1438355 , -0.06882065, -0.49928009, -0.66920766,
         -0.54022649],
        [ 1.80074855, -1.08901229, -1.23582281,  1.66758504,
          0.55487304]],

       [[ 1.00297554,  0.30631624,  0.42869907,  1.97868335,
          0.69192854],
        [ 1.63914394, -1.67463226,  1.17718837,  0.31112613,
         -0.27363147],
        [ 0.80390793,  1.18591072,  0.32199584, -1.30108795,
          1.03982799],
        [ 1.17254232,  1.99842926, -1.26996018,  2.06173294,
          0

## np.save('path,array')とnp.load('path')

In [156]:
ndarray = np.random.randn(3, 4, 5)
ndarray.shape

(3, 4, 5)

In [157]:
np.save('sample_ndarray', ndarray)

In [159]:
loaded_ndarray = np.load('sample_ndarray.npy')
loaded_ndarray.shape

(3, 4, 5)

In [160]:
dictionary ={
    'id': 123456,
    'image': ndarray
}

In [161]:
np.save('sample_dict.npy', dictionary)

In [166]:
loaded_dict = np.load('sample_dict.npy', allow_pickle=True)[()]

In [164]:
a = np.array({'a': 1})

In [165]:
a[()]

{'a': 1}

In [167]:
type(loaded_dict)

dict