# Numpy

In [1]:
import numpy as np

## Numpy Arrays(ndarray)

In [4]:
np.array([1, 2, 3])

array([1, 2, 3])

In [13]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=complex)

In [10]:
type(matrix[0][0])

numpy.int64

In [14]:
matrix

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j],
       [7.+0.j, 8.+0.j, 9.+0.j]])

In [15]:
ndarray = np.array([1, 2, 3], dtype=np.uint8) # unsigned + - integer 8bit

In [17]:
ndarray

array([1, 2, 3], dtype=uint8)

In [18]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [19]:
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
array1 + array2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

## Shape

In [23]:
ndarray = np.array([[1, 2], [3, 4], [5, 6]])
ndarray

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
ndarray.shape

(3, 2)

In [34]:
ndarray.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
ndarray1 = np.array([1, 2, 3])
ndarray2 = np.array([[1, 2, 3]])

In [27]:
ndarray1

array([1, 2, 3])

In [28]:
print(ndarray1.shape)

(3,)


In [30]:
ndarray2

array([1, 2, 3])

In [33]:
print(ndarray2.shape)

(1, 3)


In [37]:
expand_ndarray = np.expand_dims(ndarray1, axis=1)

In [38]:
expand_ndarray.shape

(3, 1)

In [39]:
np.squeeze(expand_ndarray)

array([1, 2, 3])

In [40]:
expand_ndarray

array([[1],
       [2],
       [3]])

In [45]:
ndarray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
ndarray.shape

(3, 3)

In [46]:
ndarray.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])